export const CHECKOUT_UPDATE_DETAILS = 'CHECKOUT_UPDATE_DETAILS';
export const CHECKOUT_SAVE_SHIPPING_ADDRESS = 'CHECKOUT_SAVE_SHIPPING_ADDRESS';
export const CHECKOUT_SAVE_PAYMENT_METHOD = 'CHECKOUT_SAVE_PAYMENT_METHOD';
export const CHECKOUT_EMPTY = 'CHECKOUT_EMPTY';
